### ISSUE TITLE
FMAT LFP format from getLFP is not compatible with neurocode functions. 

### ISSUE THREAD

**Issue by lolaBerkowitz** [ayalab1/neurocode#3] opened 2022-10-20 21:18 UTC
FMAT format of [timestamps x nChannels] is not compatible with following: 

* WaveSpec 
* CFCPhaseAmp

Are these functions still being used or are there FMA alternatives that can take their place?

**Comment by raltodo** [comment] 2022-10-20 21:41
Thanks for spotting these! We should update them, but in the meantime, you should be able to call them, as well as any other non-updated function, with this simple converter function: lfp2struct

[lfp,metadata] = getLFP(channels)
CFCPhaseAmp(lfp2struct(lfp,metadata))

**Comment by lolaBerkowitz** [comment] 2022-10-22 03:29
Okay, so a problem arose with the patch in that it duplicates the amount of data held in memory and now some scripts are giving out-of-memory errors. 

Probably best to revert getLFP.m to the prior version. The FMAT format can be developed in a branch in order to test the functionality of the format within the repo.

**Comment by AntonioFR8** [comment] 2022-10-22 13:08
Thanks Laura. This looks like an important problem. Why does the FMAT LFP occupies more memory? Is it because of the precession it is stored with?

**Comment by lolaBerkowitz** [comment] 2022-10-22 13:59
It is because during the conversion from the matrix [ts nchannels] to structure you're duplicating the matrix and holding both the matrix and structure format in memory. 

For example, in PickSWTHChannel_km, the matrix was loaded, and then the data was stored again in a structure format as the input to bz_PowerSpectrumSlope requires this. This was unusable for long sessions. The problem was [resolved](https://github.com/ayalab1/neurocode/commit/ba49fbacac168541ce3eec0f6146dd737453f793) by loading the structure format only (via loadbinary).  

Likewise, getLFP itself has the same issue whereby the data is stored in a structure and then duplicated on line 226 to output the FMAT matrix. 

One fix would be to use memmap to reduce memory burden as chunks would be loaded into memory as needed. A more straightforward fix would be to load the data into its final format directly to avoid duplication.

**Comment by AntonioFR8** [comment] 2022-10-22 14:35
You are right, that sounds like a bad way of doing things. Data should not be duplicated, just saved in its final format directly

**Comment by raltodo** [comment] 2022-10-23 22:48
I just want to clarify that this is an issue with the temporary patch, and this was not meant to be a permanent solution, but a quick fix to run functions we haven't edited yet. I edited all functions that call getLFP directly, but these functions don't call it, so it's less obvious to find them.

**Comment by ryanharvey1** [comment] 2022-12-06 03:31
The issue is resolved by reverting getLFP.

https://github.com/ayalab1/neurocode/commit/7cd3a681719c59dbc60dc321cf822615a1e5aa65

**Closed by ryanharvey1** 2022-12-06 03:31 UTC
